### ISSUE TITLE
Checklist for website MVP

### ISSUE THREAD

**Issue by bitspittle** [bitspittle/racketeer#1]
# Required for Playtesters
Features necessary for us to feel comfortable bringing in users to playtest
- [x] Title screen
- [X] Add a version to the UI
- [X] Auto-saving / restoring game (locally) at the beginning of every turn
- [x] Cannot activate reason (don't disable card but show a popup?)
- [x] History (and text updates in a scroll area)
- [x] Summary screen
- [x] Allow toggling features when starting the game
- [x] Saving user data (locally) such as cards seen and buildings used
   - [x] Add an indicator for "never seen before" card
- [X] Menu:
  - [x] View all cards in the game (with searching)
  - [x] Card List
  - [x] Building list
  - [x] Userdata
  - [X] Clear user data
  - [X] Restart (different from Save & Quit!)
  - [x] Save & Quit (return to title, don't send data to server)
  - [x] Quit (return to title, send data to server)
- [x] Site auth!
- [x] Saving analytics (remotely. Firebase DB? Upload to Google drive?)
- [x] Favicon
- [x] Cloud sync
  - [x] Finished games
  - [x] Aborted games
  - [x] Crashes
- [x] Button for menu
- [x] Highlight reroll / expand
- [x] Basic Analytics
- [x] Settings live in the cloud

# Want to have
- [x] Jump into menu with deep link
- [x] Keep scrollbar positions
- [ ] Unlocks
- [ ] Show emoji for shop / street tweaks
- [ ] Show price difference in label (see also Fashion Runway)
- [ ] Card vars
- [ ] Max 100 cards?
- [ ] Discord link somewhere
- [ ] Static instructions
- [x] Consistent seed behavior

# Polish
Features that are important for the game to feel juicy
- [ ] Flavor
- [ ] Cards should have outlines. Piles should look like piles of cards.
- [ ] a11y: Make sure you can play a game with just the keyboard
- [ ] Animations (cards transition to their destination, score values pulse if changed)
- [ ] Portraits (AI generated for now?)
- [ ] Allow being played on smaller screens
- [ ] Choose screen shows cards directly?
- [ ]  Admin Menu
  - [ ] Scripting console
- [ ] Ads
- [ ] Graph on summary screen
- [ ] Remove parens from all buttons; standardize 5.px gap to a single Composable / constant?
- [ ] Browse all should say when no match is found
- [ ] Buildings should have a message when the feature is disabled (especially telling new users how to unlock it)
- [ ] In game send feedback (with game snapshot)

# Nice to have
- [ ] Mobile support
- [ ] Interactive instructions
- [ ] Daily Leaderboard
- [ ] Resume game on reload? But somehow avoid people cheating for cancellable choices. Can we restore to the choice?
- [ ] Send feedback should have an option to snapshot the game
- [ ] Cheat detection, avoid playing multiple copies of the same game at the same time.

---

# Critical 
Minimal necessary for being able to play through a game
- [x] Piles
- [x] The shop
- [x] Visible console
- [x] Choices (probably hard)
- [x] Tooltips
- [x] Adjectives: Swift, etc.
- [x] Counters
- [x] Expendable missing
- [x] Buildings
- [x] View pile
- [x] Buildings missing activation costs
- [x] Visually distinguish blueprints from buildings
- [x] Choice: Say which pile a card is in

# Required for design
- [x] Some way to enable / disable admin mode
- [X] Admin menu
  - [x] Create a card
  - [x] Build a building
  - [X] Move cards (press A to toggle all)
  - [x] Download a game snapshot / load a game snapshot from disk
  - [x] Link to API
  - [x] Upgrade a card
- [x] Add a special admin-only load button on the title screen
